### ISSUE TITLE
Error undefined variable

### ISSUE THREAD

**Issue by laurensiusadi** [lucianmarin/pressdown#2]
![image](https://user-images.githubusercontent.com/5661040/79825634-c67a8100-83c3-11ea-9a5a-a6cd76c43adc.png)

![image](https://user-images.githubusercontent.com/5661040/79825644-cd08f880-83c3-11ea-94e8-d212aab6a50a.png)

**Comment by lucianmarin** [comment]
I fixed PHP >7.2 compatibility on develop branch.
